server {
    listen 80;
    server_name bayar-todo.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bayar-todo.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/bayar-todo.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bayar-todo.duckdns.org/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}